### PR TITLE
Fix assertion: IgnoreValue don't work

### PR DESCRIPTION
**Pull request by cazacutudor**
The problem: m.ignoreValue constant don't working.

This pull-request will:
- fix ignoreValue issue
- cover empty expectedArgs

Test Spec:
```
'@Only
'@Test reported case
'@Params[52, [52], true]
'@Params[invalid, [invalid], true]
'@Params["42", ["42"], true]
'@Params[42, ["#ROIBOS#IGNORE_VALUE"], true]
'@Params[42, [invalid], false]
'@Params[42, invalid, true]
'@Params[42, [], true]
function assertMocks_test_spec(value, expected, mockPass) as void
    obj = {
        foo: function(arg0) : return arg0 : end function
    }
     m.ExpectOnce(obj, "foo", expected)
    obj.foo(value)
    m.isAutoAssertingMocks = false
    m.AssertMocks()

    isFail = m.currentResult.isFail
    m.currentResult.Reset()
    m.CleanMocks()
    m.AssertEqual(isFail, not mockPass)
end function
```

### CODE REVIEW

**Comment by georgejecook** [comment]
Thanks but I fixed this just now

1. I've fixed it in 64c886d5739d7c08189a8555f87304696d03f81d, with just a slight change to if statement
2. I don't know why you removed the notion of `invalidValue` - this allows a testcase to explicitly state it's expecting the value invalid, indicating that rooibos should thrown an error if it did _not_ receive invalid. Please refer to : https://github.com/georgejecook/rooibos/blob/master/docs/index.md#specifying-an-expected-value-of-invalid-with-minvalidvalue

**Comment by georgejecook** [comment]
did you read the docs link, I included?
it’s a core part of the expect functionality. It’s not a random piece of code.
the fix I introduced passes all tests cases, and is a slight move of the _and_, so that fix will stay.
I prefer that to removing core features, and introducing more code/checks, when just slightly changing the if to have the correct logic works.

polite reminder: please let's conduct all conversations to prs here. Thanks.

**Comment by cazacutudor** [comment]
> Thanks but I fixed this just now
> 
> 1. I've fixed it in [64c886d](https://github.com/georgejecook/rooibos/commit/64c886d5739d7c08189a8555f87304696d03f81d), with just a slight change to if statement
> 2. I don't know why you removed the notion of `invalidValue` - this allows a testcase to explicitly state it's expecting the value invalid, indicating that rooibos should thrown an error if it did _not_ receive invalid. Please refer to : https://github.com/georgejecook/rooibos/blob/master/docs/index.md#specifying-an-expected-value-of-invalid-with-minvalidvalue

2. I get you point. Anyway, i'm not sure we need a `m.invalidValue` just to specify we expecting an invalid value. I think we can just use `invalid` for that.

If you look on line https://github.com/georgejecook/rooibos/commit/64c886d5739d7c08189a8555f87304696d03f81d#diff-3b953cb89b8649a5ba1713f377e5fd3aR1006
we converting m.invalidValue into invalid... so the result will be the same even if you use `m.invalidValue` or `invalid`

I always trying to keep things simple, as a best practice.
Was there any reason why you decided to add that complexity ?

**Comment by cazacutudor** [comment]
Beside that, this pull request added support for empty arrays. 

Right now if you trying to execute `m.ExpectOnce(obj, "foo", [])` you will get: 
image

From my point an empty array should be treated like invalid, so all the args will be set by default as `ignoreValue`.

Please tell me what do you think.

**Comment by georgejecook** [comment]
okay - I don't see a point in that.. I think that `invalid`, is a clearer intent, and is documented as such:

`You may also really not care about the args, in which case you can set that value to invalid and the call to m.AssertMocks() will skip checking the invoked args.`

https://github.com/georgejecook/rooibos/blob/master/docs/index.md#specifying-expected-invocation-arguments

I'm happy to add interpretation of `[]` as `invalid`, if you have a good reason to do so - perhaps you feel it's more concise? In which case raise an issue.

**Comment by cazacutudor** [comment]
Let's take it again, step by step.
Probably i don't understood the intent of the `m.invalidValue`.

The will be any difference in result of
`m.ExpectOnce(obj, "foo", [invalid])` vs `m.ExpectOnce(obj, "foo", [m.invalidValue])` ?

About treated of `[]` as `invalid` i put my example, and point of view, in a comment above. If is somethings unclear there we can get in touch, and talk about it.

P.S. I was not bad intended, first time when i looked over the project, as an outsider, that constant was not looking like something that have a role. I know is also defined in description and all over the places. But my doubt was: We really need that ? What the reason why we have that `m.invalidValue` there. I'm just trying to help, on doing things even better then they are.

**Comment by georgejecook** [comment]
That’s fair enough; but I won’t approve PR’s that rip out features that are
documented, with code examples, without the docs being updated and a
conversation first.

In this case, I opted to use m.invalidValue and m.ignoreValue because we
need both of those features. We need to be able to say - I don’t care if
this value is different or not, and I expect this value to be invalid.

It might be that m.invalidValue can be gotten rid of; let me think on it.
If it can, we need to update the relevant section of the docs.

I’m hesitant, because I recall I had a use-case to differentiate `value
should be invalid`, `ignored`, and `value is not expected`; but I can’t
think of it right now.

I’ll get back to you.



On October 24, 2018 at 1:28:47 PM, Cazacu Tudor (notifications@github.com)
wrote:

Let's take it again, step by step.
Probably i don't understood the intent of the m.invalidValue.

The will be any difference in result of
m.ExpectOnce(obj, "foo", [invalid]) vs m.ExpectOnce(obj, "foo",
[m.invalidValue]) ?

About treated of [] as invalid i put my example, and point of view, in a
comment above. If is somethings unclear there we can get in touch, and talk
about it.

P.S. I was not bad intended, first time when i looked over the project, as
an outsider, that constant was not looking like something that have a role.
I know is also defined in description and all over the places. But my doubt
was: We really need that ? What the reason why we have that m.invalidValue
there. I'm just trying to help, on doing things even better then they are.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/georgejecook/rooibos/pull/19#issuecomment-432775130>,
or mute the thread

**Pull request closed without merging**
