### PR TITLE
Fix ubuntu ci

### PR DESCRIPTION
**Pull request by cewert**
fix typo in OS matrix

### CODE REVIEW

**Review by TwitchBronBron — APPROVED** [review]

**Comment by cewert** [comment]
Attempted to fix the linting errors. Please review before merging

Edit: still [getting errors](https://github.com/cewert/rooibos/actions/runs/4520043411/jobs/7960893713#step:5:2) but not sure why. I believe I am using the [correct syntax](https://www.typescriptlang.org/docs/handbook/modules.html#importing-types)

**Review by TwitchBronBron — APPROVED** [review]

**Review by georgejecook — APPROVED** [review]

**Comment by TwitchBronBron** [comment]
@cewert, please check out the latest [CI failure](https://github.com/georgejecook/rooibos/actions/runs/4520011524/jobs/7982561984?pr=217), there are a bunch of errors. Can you resolve those as well?

**Comment by cewert** [comment]
@TwitchBronBron I'm not sure what's causing those errors but I'd be happy to fix them if you can point me in the right direction.

**Comment by TwitchBronBron** [comment]
@cewert the vscode extension only runs eslint against open files. So most likely these are just other files that are failing the same lint rules that you hadn't opened before. 

To view the full list of errors, you can run this command:
```bash
cd ./bsc-plugin
npm run preversion
```

It'll print out a whole list of lint errors that need to be fixed.

**Comment by cewert** [comment]
@TwitchBronBron Thanks 👍 

I don't see any of the above CI errors listed when I run that command locally. The CI errors have something to do with importing types since it's complaining about the import statements I modified in the first commit to fix the first set of linting errors. Notice how the CI is only throwing errors for the lines importing `type`:

rooibos-ci-error-log


rooibos-ci-error

**Comment by cewert** [comment]
The bsc-plugin is using an [older version of typescript](https://github.com/georgejecook/rooibos/blob/master/bsc-plugin/package.json#L43). I believe that is why the local linting errors are not matching

Edit: upgrading typescript in the bsc-plugin [fixed the CI errors](https://github.com/cewert/rooibos/actions/runs/4533180481/jobs/7985640714) about the type imports. It also fixed all except one of the local errors spit out by `npm run preversion`. Now they both are showing the same error from node_modules below. Shouldn't we be excluding node_modules from our linting checks?

```
node_modules/@types/node/globals.d.ts(72,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'AbortSignal' must be of type '{ new (): AbortSignal; prototype: AbortSignal; abort(reason?: any): AbortSignal; timeout(milliseconds: number): AbortSignal; }', but here has type '{ new (): AbortSignal; prototype: AbortSignal; }'.
```

**Comment by cewert** [comment]
The error changed again after updating all the other dependencies for `bsc-plugin`. 
bsc-plugin-error

It seems like we just need to exclude `node_modules` from the typescript compiler. It looks like you've already tried that in the `tsconfig.json`:
```
"exclude": [
    "node_modules/**/*"
  ],
```

I'm not very familiar with typescript so I'm not sure where to go from here. Please advise.

**Comment by TwitchBronBron** [comment]
I'll pull it down and try to get it all ironed out. Thanks for trying!

**Comment by TwitchBronBron** [comment]
@cewert I believe this PR can be closed because I resolved the issues in #219 ?

**Comment by cewert** [comment]
@TwitchBronBron that works for me 👍  FYI the import changes for [this commit](https://github.com/georgejecook/rooibos/pull/217/commits/94cb88a9b4999c39d3586e97bb853f0aadd86246) didn't make it into your PR

**Comment by TwitchBronBron** [comment]
> @TwitchBronBron that works for me 👍 FYI the import changes for [this commit](https://github.com/georgejecook/rooibos/pull/217/commits/94cb88a9b4999c39d3586e97bb853f0aadd86246) didn't make it into your PR

I tweaked the lint rules, so those should no longer be required to be fixed. I didn't see them happening locally or on the CI.

**Comment by cewert** [comment]
Closing in favor of #219

**Comment by TwitchBronBron** [comment]
Thanks for you efforts in this PR. I'm a seasoned Node.js/typescript developer and It took me a good hour to work through all the quirks in #219 to figure out how to make it work properly. it was quite a pain! :)

**Comment by cewert** [comment]
Thanks that makes me feel a bit better 😛 I figured the error messages were a red herring I just couldn't nail down the actual issue. Interesting that `package-lock.json` was the cause. Nice job!

**Pull request closed without merging**
