### PR TITLE
Code coverage fixes

### PR DESCRIPTION
**Pull request by arturocuya**

### CODE REVIEW

**Comment by TwitchBronBron** [comment]
Wow, I would have expected this take a lot more effort to implement. Nicely done!

**Comment by arturocuya** [comment]
@TwitchBronBron these commits go into an existing branch that has most of the changes. It just needed to get through the finish line :)

**Comment by TwitchBronBron** [comment]
Oh! I totally hadn't realized it. Nice.

**Review by georgejecook — APPROVED** [review]

**Comment by georgejecook** [comment]
Thanks for finishing that @arturocuya - what I saw looked good; I'm not sure if we're reporting correctly _yet_ - I've got a few full-on days; but will run some coverage scenarios to see what happens.

**Pull request merged**
